# Copyright (c) 2026 Anomly, Inc. All rights reserved. Author: Ry Bruscoe.
"""
invar.license — Ed25519-signed license files. The license IS a receipt: a canonical
JSON manifest signed by Anomly's issuing key, verified OFFLINE by the agent with the
embedded public key. No license server, no phone-home, no activation flow — aligned
with the product's own no-cloud promise and trivial to manage:

  issue : python3 -m invar.license issue --key anomly_issuing.key \
            --email a@b.c --tier ledger --seats 25 --expires 2027-08-20
  verify: python3 -m invar.license verify license.invar
  agent : invar.license.check("license.invar") -> License | None

Key management (Anomly side): ONE Ed25519 keypair. Private key lives with Ry
(generated by `python3 -m invar.license keygen`, kept offline / in Stripe-webhook
host env). Public key is pinned below and ships in every agent. Rotations append
to TRUSTED_KEYS. Subscriptions get an `expires` date (re-issued on renewal by the
Stripe webhook); perpetual device licenses omit it.

Free tier needs NO license: the agent runs fully without one. A license unlocks
Ledger/team features only — so a cracked license gains nothing an honest free
user doesn't already have locally, which keeps enforcement honest and low-stakes.
"""
from __future__ import annotations

import argparse
import base64
import datetime as _dt
import json
import os
import sys

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey, Ed25519PublicKey)

# Anomly issuing public key(s), base64 raw — ships pinned in every agent.
TRUSTED_KEYS = [
    # Anomly production issuing key (ceremony 2026-08-20, Ry Bruscoe)
    "zbUvsmR6rjyFUFhJfKeeCj60qHjXTTzJS3HjeRbmcQU=",
]

TIERS = ("founding-device", "ledger", "pro")


def _canon(obj) -> bytes:
    return json.dumps(obj, separators=(",", ":"), sort_keys=True).encode()


def keygen(path: str) -> str:
    sk = Ed25519PrivateKey.generate()
    raw = sk.private_bytes_raw()
    pub = base64.b64encode(sk.public_key().public_bytes_raw()).decode()
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "wb") as f:
        f.write(base64.b64encode(raw))
    return pub


def issue(key_path: str, email: str, tier: str, seats: int,
          expires: str | None) -> dict:
    assert tier in TIERS, f"tier must be one of {TIERS}"
    sk = Ed25519PrivateKey.from_private_bytes(
        base64.b64decode(open(key_path, "rb").read()))
    manifest = {
        "invar_license": "1",
        "email": email,
        "tier": tier,
        "seats": seats,
        "issued": _dt.date.today().isoformat(),
    }
    if expires:
        manifest["expires"] = expires
    sig = sk.sign(_canon(manifest))
    return {"manifest": manifest,
            "sig": base64.b64encode(sig).decode(),
            "pub": base64.b64encode(sk.public_key().public_bytes_raw()).decode()}


class License:
    def __init__(self, manifest: dict):
        self.email = manifest["email"]
        self.tier = manifest["tier"]
        self.seats = int(manifest["seats"])
        self.expires = manifest.get("expires")

    def expired(self) -> bool:
        return (self.expires is not None
                and _dt.date.today().isoformat() > self.expires)


def check(path: str, trusted: list[str] | None = None) -> License | None:
    """Verify a license file offline. Returns License, or None with the reason
    printed to stderr. The signing key must be in the trusted list AND the
    signature must verify AND the license must not be expired."""
    trusted = trusted if trusted is not None else TRUSTED_KEYS
    try:
        blob = json.load(open(path))
        pub_b64 = blob["pub"]
        if pub_b64 not in trusted:
            print("license: signing key is not an Anomly issuing key",
                  file=sys.stderr)
            return None
        pk = Ed25519PublicKey.from_public_bytes(base64.b64decode(pub_b64))
        pk.verify(base64.b64decode(blob["sig"]), _canon(blob["manifest"]))
        lic = License(blob["manifest"])
        if lic.expired():
            print(f"license: expired {lic.expires}", file=sys.stderr)
            return None
        return lic
    except InvalidSignature:
        print("license: signature INVALID", file=sys.stderr)
        return None
    except Exception as e:
        print(f"license: unreadable ({e})", file=sys.stderr)
        return None


def main():
    ap = argparse.ArgumentParser(prog="invar-license")
    sub = ap.add_subparsers(dest="cmd", required=True)
    kg = sub.add_parser("keygen"); kg.add_argument("--out", default="anomly_issuing.key")
    isu = sub.add_parser("issue")
    isu.add_argument("--key", required=True); isu.add_argument("--email", required=True)
    isu.add_argument("--tier", required=True, choices=TIERS)
    isu.add_argument("--seats", type=int, default=1)
    isu.add_argument("--expires", default=None)
    isu.add_argument("--out", default="license.invar")
    ver = sub.add_parser("verify"); ver.add_argument("license")
    ver.add_argument("--trust-pub", default=None,
                     help="dev override: additionally trust this base64 pubkey")
    a = ap.parse_args()
    if a.cmd == "keygen":
        pub = keygen(a.out)
        print(f"private key: {a.out}  (chmod 600 — keep offline)")
        print(f"public key : {pub}")
        print("-> paste the public key into TRUSTED_KEYS in invar/license.py")
    elif a.cmd == "issue":
        blob = issue(a.key, a.email, a.tier, a.seats, a.expires)
        json.dump(blob, open(a.out, "w"), indent=1)
        print(f"issued {a.tier} x{a.seats} to {a.email} -> {a.out}")
    elif a.cmd == "verify":
        trusted = TRUSTED_KEYS + ([a.trust_pub] if a.trust_pub else [])
        lic = check(a.license, trusted)
        if lic:
            exp = lic.expires or "perpetual"
            print(f"VALID: {lic.tier} x{lic.seats} for {lic.email} ({exp})")
            sys.exit(0)
        print("INVALID")
        sys.exit(1)


if __name__ == "__main__":
    main()
